@url= https://8080-juaanlxx-swgames2024-xslf6ukilg5.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome":"bBBE"
}

###
DELETE {{url}}/plataformas/2


###

PUT {{url}}/plataformas/5
Content-Type: application/json

{
    "nome": "rErE"
}
